version: '3'
services:
  db:
    container_name: pharmacy-finder-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: pharmacy_management
    volumes:
      - './docker/mysql:/var/lib/mysql'
  phpmyadmin:
    container_name: pharmacy-finder-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '${PHPMYADMIN_PORT}:80'
    depends_on:
      - db
  api:
    container_name: pharmacy-finder-api
    image: openjdk:17.0.2-jdk
    ports:
      - '${APP_PORT}:8080'
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    entrypoint: [ 'sh', '-c', 'chmod u+x ./mvnw && ./mvnw spring-boot:run' ]
