spring:
  datasource:
    url: jdbc:mysql://mysql:3306/pharmacy_management
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui
application:
  security:
    allowed-origin: http://localhost:5173
    jwt:
      secret-key: 6250655368566D597133743677397A24432646294A404D635166546A576E5A72
      expiration: 86400000 # 1 day
